### ISSUE TITLE
@uplift/strings cannot be used with client-side Remix

### ISSUE THREAD

**Issue by nakleiderer** [uplift-ltd/nexus#348]
When using Remix, `@uplift/strings` fails if it is used in client side code. This is because of the following import tree:
1. `https://github.com/uplift-ltd/nexus/blob/master/packages/strings/src/index.ts` imports
2. `https://github.com/uplift-ltd/nexus/blob/master/packages/strings/src/urls.ts` imports
3. `@uplift-ltd/constants` which imports 
4. `https://github.com/uplift-ltd/nexus/blob/master/packages/constants/src/index.ts` that references
5. `process.env`

Since `process.env` doesn't exist in the client (and Remix doesn't do compile-time replacements like NextJS), this fails.

Currently, this library can only be used server-side unless the consumer polyfills `process.env`. The library can be exported from a `*.server.ts` file to ensure it's never loaded on the client.

**Comment by mariusc23** [comment]
@nakleiderer Hm, I haven't tried remix yet. How does `*.server.ts` work? Mainly, how do we keep compatibility with with other frameworks? Do we just rename `constants.ts` to `constants.server.ts` and point `index.ts` to export `constants.server`? Or would the remix client still load the code if you specifically import `*.server`?

We also use `process.env` in `urls.ts` which we'll have to update.

**Comment by nakleiderer** [comment]
Refactoring any code that's intended to run on the client so it doesn't assume the existence of `process.env` is the best way to be compatible. Frameworks like NextJS automatically inject process.env, but if someone were to attempt a vanilla React project, this would blow up for them as well. Using `process.env` assumes the consumer of the library uses specific build tools that define `process.env`

For this project, I think the easiest way to solve this would be to have this line at the top of any file using the node process global:
`const process = globalThis.process || { env: {} }`

`globalThis` is available on the client and on the server, so this code can safely run anywhere. If it's on the server environment, the process data will be found. If it's on the client, it'll fall back to an env shim.

 https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis

**Comment by mariusc23** [comment]
That makes sense! Wanna PR it?
